### ISSUE TITLE
navier-stokes

### ISSUE THREAD

**Issue by jviquerat** [pmocz/finitevolume-python#2]
Hi,

Thanks for the very neat blog post and code, it is very helpful.
I am definitely not an expert in finite volumes, but I was wondering if there was anything preventing from extending the present collocated finite volume formulation to the navier-stokes equations ? I see on the internet that most formulations for NS are staggered, or use specific time-stepping techniques when they are not.

Best,

**Comment by pmocz** [comment]
Excellent question! This non-staggered approach is robust for the compressible Euler equations, but incompressible NS often uses staggering for the velocity field (because it's a more natural way to represent a divergence-free field) and that discretization can be also used for the compressible case.

**Comment by jviquerat** [comment]
Thanks for the answer ;)
